### ISSUE TITLE
Duplicate symbol when building

### ISSUE THREAD

**Issue by fellipecaetano** [brynbellomy/iOS-GTLYouTube#1]
duplicate symbol _OBJC_METACLASS_$_GTLQueryYouTube in:
    /Users/macmini/projetos/MultimediaSearchPoc/DerivedData/MultimediaSearchPoc/Build/Products/Debug-iphonesimulator/libPods.a(GTLYouTube_Sources.o)
    /Users/macmini/projetos/MultimediaSearchPoc/DerivedData/MultimediaSearchPoc/Build/Products/Debug-iphonesimulator/libPods.a(GTLQueryYouTube.o)
duplicate symbol _OBJC_CLASS_$_GTLQueryYouTube in:
    /Users/macmini/projetos/MultimediaSearchPoc/DerivedData/MultimediaSearchPoc/Build/Products/Debug-iphonesimulator/libPods.a(GTLYouTube_Sources.o)
    /Users/macmini/projetos/MultimediaSearchPoc/DerivedData/MultimediaSearchPoc/Build/Products/Debug-iphonesimulator/libPods.a(GTLQueryYouTube.o)
duplicate symbol _OBJC_CLASS_$_GTLServiceYouTube in:
    /Users/macmini/projetos/MultimediaSearchPoc/DerivedData/MultimediaSearchPoc/Build/Products/Debug-iphonesimulator/libPods.a(GTLYouTube_Sources.o)
    /Users/macmini/projetos/MultimediaSearchPoc/DerivedData/MultimediaSearchPoc/Build/Products/Debug-iphonesimulator/libPods.a(GTLServiceYouTube.o)
duplicate symbol _OBJC_METACLASS_$_GTLServiceYouTube in:
    /Users/macmini/projetos/MultimediaSearchPoc/DerivedData/MultimediaSearchPoc/Build/Products/Debug-iphonesimulator/libPods.a(GTLYouTube_Sources.o)
    /Users/macmini/projetos/MultimediaSearchPoc/DerivedData/MultimediaSearchPoc/Build/Products/Debug-iphonesimulator/libPods.a(GTLServiceYouTube.o)
ld: 4 duplicate symbols for architecture i386

**Comment by brynbellomy** [comment]
Try removing `GTLYouTube_Sources.m` from the `Pods` project in your workspace.  I think I hit this issue a few weeks back but forgot to commit a fix.  Let me know if this helps, and if so, I'll finally get that commit up here.

**Comment by brynbellomy** [comment]
Also, are you working with `v0.0.3`?

**Comment by fellipecaetano** [comment]
It works! Thanks (:

PS: Yes, I'm using v0.0.3

**Comment by brynbellomy** [comment]
Fixed -- pushed v0.0.4 to CocoaPods
